backend/GoodBuyAPI/Models/Entry.cs
using System;
using System.ComponentModel.DataAnnotations;

namespace GoodBuyAPI.Models
{
    public class Entry
    {
        [Key]
        public ulong BarcodeId { get; set; }
        public string Name { get; set; }
        public string Link { get; set; }

        [Display(Name = "Created Date")]
        [DataType(DataType.Date)]
        [DisplayFormat(DataFormatString = "{0:dd-MM-yyyy}", ApplyFormatInEditMode = true)]
        public DateTime CreatedDate { get; set; }
    }
}

backend/GoodBuyAPI/Controllers/EntriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using GoodBuyAPI.Models;
using Microsoft.AspNetCore.Authorization;
using X.PagedList;

namespace GoodBuyAPI.Controllers
{
    [Authorize]
    public class EntriesController : Controller
    {
        private readonly MyDatabaseContext _context;

        public EntriesController(MyDatabaseContext context)
        {
            _context = context;
        }

        // GET: Entries
        /// <summary>
        /// Main page callback.
        /// </summary>
        /// <param name="sortOrder">/?SortOrder={sortOrder}
        /// Parameter to sort the list
        /// </param>
        /// <param name="currentFilter">/?SortOrder={sortOrder}&currentFilter={filter}
        /// Parameter of search. If you search items and want to sort them, this parameter will be used.
        /// </param> 
        /// <param name="searchString">/?SearchString={searchString}
        /// Parameter to search the list of entries and return matching ones.
        /// </param>
        /// <param name="page">/?page={page}
        /// Page number. By default (on main page) is 1.
        /// </param>
        /// <returns>View of main page.</returns>
        [AllowAnonymous]
        public async Task<IActionResult> Index(string sortOrder, string currentFilter, string searchString, int? page)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.NameSortParam = sortOrder == "Name" ? "name_desc" : "Name";
            ViewBag.DateSortParam = sortOrder == "Date" ? "date_desc" : "Date";
            ViewBag.IdSortParam = String.IsNullOrEmpty(sortOrder) ? "identity_desc" : "";

            if (searchString != null)
            {
                page = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewBag.CurrentFilter = searchString;

            var entries = from s in _context.EntriesList select s;

            if (!String.IsNullOrEmpty(searchString))
            {
                //TODO: Improve searching? Is Contains really good enough?
                entries = entries.Where(s => s.Name.Contains(searchString)
                                             || s.BarcodeId.ToString().Contains(searchString));
            }

            switch (sortOrder)
            {
                case "name":
                    entries = entries.OrderBy(s => s.Name);
                    break;
                case "name_desc":
                    entries = entries.OrderByDescending(s => s.Name);
                    break;
                case "date":
                    entries = entries.OrderBy(s => s.CreatedDate);
                    break;
                case "date_desc":
                    entries = entries.OrderByDescending(s => s.CreatedDate);
                    break;
                case "identity_desc":
                    entries = entries.OrderByDescending(s => s.BarcodeId);
                    break;
                default:
                    entries = entries.OrderBy(s => s.BarcodeId);
                    break;
            }

            int pageSize = Common.PageSize;
            int pageNumber = (page ?? 1);

            return View(await entries.ToPagedListAsync(pageNumber, pageSize));
        }

        #region BeautifulView
        // GET: Entries/Details/5
        //public async Task<IActionResult> Details(ulong? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var entry = await _context.EntriesList
        //        .FirstOrDefaultAsync(m => m.BarcodeId == id);
        //    if (entry == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(entry);
        //}
        #endregion

        // GET: Entries/Details/5
        /// <summary>
        /// Details page. Is used to return a JSON document for API callback.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        [AllowAnonymous]
        public async Task<ActionResult<Entry>> Details(ulong? id)
        {
            var entryItem = await _context.EntriesList.FindAsync(id);
            if (entryItem == null)
            {
                return NotFound();
            }

            return entryItem;
        }

        // GET: Entries/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Entries/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("BarcodeId,Name,Link,CreatedDate")] Entry entry)
        {
            if (ModelState.IsValid)
            {
                _context.Add(entry);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(entry);
        }

        // GET: Entries/Edit/5
        public async Task<IActionResult> Edit(ulong? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entry = await _context.EntriesList.FindAsync(id);
            if (entry == null)
            {
                return NotFound();
            }
            return View(entry);
        }

        // POST: Entries/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ulong id, [Bind("BarcodeId,Name,Link,CreatedDate")] Entry entry)
        {
            if (id != entry.BarcodeId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(entry);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EntryExists(entry.BarcodeId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(entry);
        }

        // GET: Entries/Delete/5
        public async Task<IActionResult> Delete(ulong? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entry = await _context.EntriesList
                .FirstOrDefaultAsync(m => m.BarcodeId == id);
            if (entry == null)
            {
                return NotFound();
            }
            
            return View(entry);
        }

        // POST: Entries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(ulong id)
        {
            var entry = await _context.EntriesList.FindAsync(id);
            _context.EntriesList.Remove(entry);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EntryExists(ulong id)
        {
            return _context.EntriesList.Any(e => e.BarcodeId == id);
        }
    }
}

backend/GoodBuyAPI/Views/Entries/Create.cshtml
@model GoodBuyAPI.Models.Entry

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Entry</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="BarcodeId" class="control-label"></label>
                <input asp-for="BarcodeId" class="form-control" />
                <span asp-validation-for="BarcodeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Link" class="control-label"></label>
                <input asp-for="Link" class="form-control" />
                <span asp-validation-for="Link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" value="@DateTime.Today.ToString("{0:dd-MM-yyyy}")"/>
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

backend/GoodBuyAPI/Views/Entries/Delete.cshtml
@model GoodBuyAPI.Models.Entry

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Entry</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BarcodeId)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BarcodeId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Link)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Link)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="BarcodeId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

backend/GoodBuyAPI/Views/Entries/Details.cshtml
@model GoodBuyAPI.Models.Entry

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Entry</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BarcodeId)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.CreatedDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.CreatedDate)
        </dd>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Link)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.BarcodeId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

backend/GoodBuyAPI/Views/Entries/Edit.cshtml
@model GoodBuyAPI.Models.Entry

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Entry</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="BarcodeId" />
            <div class="form-group">
                <label asp-for="Link" class="control-label"></label>
                <input asp-for="Link" class="form-control" />
                <span asp-validation-for="Link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BarcodeId" class="control-label"></label>
                <input asp-for="BarcodeId" class="form-control" />
                <span asp-validation-for="BarcodeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreatedDate" class="control-label"></label>
                <input asp-for="CreatedDate" class="form-control" />
                <span asp-validation-for="CreatedDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

backend/GoodBuyAPI/Views/Entries/Index.cshtml
@using System.Runtime.CompilerServices
@using Microsoft.Data.SqlClient
@model X.PagedList.IPagedList<GoodBuyAPI.Models.Entry>
@using X.PagedList.Mvc.Core
@using X.PagedList.Mvc.Core.Common
<link href="~/css/PagedList.css" rel="stylesheet" type="text/css"/>

@{
    ViewData["Title"] = "Index";
    int rowNo = Model.PageNumber == 1 ? 0 : (Model.PageNumber - 1) * Common.PageSize;
    var loggedIn = User?.Identity.IsAuthenticated == true;
}

<h1>Index</h1>
@if (loggedIn)
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
}

<p>Current entry count: @Model.TotalItemCount</p>
@using (Html.BeginForm("Index", "Entries", FormMethod.Get))
{
    <p>
        Search: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string, new
           {
               @placeholder = "BarcodeId or Name",
           })
        <input type="submit" value="Search"/>
    </p>
}
<table class="table">
    <thead>
    <tr>
        <th>
            No
        </th>
        <th>
            @Html.ActionLink("Name", "Index", new
            {
                SortOrder = ViewBag.NameSortParam,
                currentFilter = ViewBag.CurrentFilter
            })
        </th>
        <th>
            Link
        </th>
        <th>
            @Html.ActionLink("BarcodeId", "Index", new
            {
                SortOrder = ViewBag.IdSortParam,
                currentFilter = ViewBag.CurrentFilter
            })
        </th>
        <th>
            @Html.ActionLink("Created Date", "Index", new
            {
                SortOrder = ViewBag.DateSortParam,
                currentFilter = ViewBag.CurrentFilter
            })
        </th>
        <th>
            Operations
        </th>
    </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>
                @(rowNo += 1)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Name, "_NameWithoutSlash")
            </td>
            <td>
                <a href="@Html.DisplayFor(modelItem => item.Link)">@Html.DisplayFor(modelItem => item.Link)</a>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BarcodeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CreatedDate)
            </td>
            <td>
                @if (loggedIn)
                {
                    <a asp-action="Edit" asp-route-id="@item.BarcodeId">Edit</a>
                    <a asp-action="Delete" asp-route-id="@item.BarcodeId">Delete</a>
                }
                <a asp-action="Details" asp-route-id="@item.BarcodeId">Details</a>
            </td>
        </tr>
    }
    </tbody>
</table>

<br/>
Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

@Html.PagedListPager(Model, page => Url.Action("Index",
    new
    {
        page,
        sortOrder = ViewBag.CurrentSort,
        currentFilter = ViewBag.CurrentFilter
    }), PagedListRenderOptions.EnableUnobtrusiveAjaxReplacing(new PagedListRenderOptions
    {
        LinkToFirstPageFormat = "<<",
        LinkToPreviousPageFormat = "<",
        LinkToNextPageFormat = ">",
        LinkToLastPageFormat = ">>",
        MaximumPageNumbersToDisplay = 5,
        DisplayEllipsesWhenNotShowingAllPageNumbers = false,
    }, new AjaxOptions() {HttpMethod = "GET", UpdateTargetId = "grid_container"}))